### ISSUE TITLE
why square dot for ij?

### ISSUE THREAD

**Issue by xuanswe** [vernnobile/MuliFont#5]
I am a developer (not designer) and want to choose a free alternative for Futura for children book.
I found this font and like it. Just one question, why do you choose `square dot` for `ij`?
Please forgive me if this question is stupid because I am not a designer, so I don't know the basic rules in this area.

**Comment by inferno986return** [comment]
I agree it would be cool to have circular tittles which is the technical term, though the decision is consistent for all the punctuation throughout the font family. I suppose they could be implemented as stylistic alternates.

**Comment by xuanswe** [comment]
Is this project and the font still alive?
